import * as fs from "node:fs";
import * as path from "node:path";

const EXAMPLES_DIR = path.resolve(__dirname, "../examples");
const OUTPUT_FILE = path.resolve(__dirname, "../lib/__registry__.ts");

function buildRegistry() {
  if (!fs.existsSync(EXAMPLES_DIR)) {
    fs.mkdirSync(EXAMPLES_DIR, { recursive: true });
  }

  const files = fs
    .readdirSync(EXAMPLES_DIR)
    .filter((f) => f.endsWith(".tsx"))
    .sort();

  const imports: string[] = [];
  const entries: string[] = [];

  for (const file of files) {
    const name = file.replace(/\.tsx$/, "");
    const source = fs.readFileSync(path.join(EXAMPLES_DIR, file), "utf-8");
    const escaped = JSON.stringify(source);

    imports.push(
      `  "${name}": {`,
      `    component: React.lazy(() => import("@/examples/${name}")),`,
      `    source: ${escaped},`,
      `  },`
    );
  }

  const output = `// This file is auto-generated by scripts/build-registry.ts
// Do not edit manually.
import React from "react";

interface RegistryEntry {
  component: React.LazyExoticComponent<React.ComponentType>;
  source: string;
}

export const registry: Record<string, RegistryEntry> = {
${imports.join("\n")}
};
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Registry built with ${files.length} examples.`);
}

buildRegistry();
