import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "next-themes",
    /^@base-ui\/.*/,
    /^@shadcn\/.*/,
    "@phosphor-icons/react",
    /^@hookform\/.*/,
    "cmdk",
    "sonner",
    "embla-carousel-react",
    "react-day-picker",
    "react-hook-form",
    "react-resizable-panels",
    "recharts",
    "input-otp",
    "zod",
    "date-fns",
  ],
  treeshake: true,
  minify: false,
});
